### ISSUE TITLE
Add 'hacktoberfest' topic to repository

### ISSUE THREAD

**Issue by Agrover112** [diptangsu/shakeabuse#8]
PR's have hacktoberfeset label but not the repo , thus making PR's inelgible according to new Updated rules.

```
PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
  The PR is merged OR
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  The PR has been approved
)
```

**Comment by diptangsu** [comment]
You mean in the about section?
![image](https://user-images.githubusercontent.com/17666381/95001605-156e4880-05e9-11eb-92fe-b76f6fba886a.png)

I did not know the repository had to have the topic.

**Comment by Agrover112** [comment]
@diptangsu  Sure no problem it was anew update by digital ocean. Thanks for adding it.
Also PR's too need hacktoberfest and hacktoberfest-accepted(if accepted)
